# kubectl get pods --selector app=App1


apiVersion: apps/v1 #Version distinta si no se pone se pisa
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
  # if it matches correctly they will function
      app: App1
      type: Front-end 
  annotations:
    buildVersion: 1.34
spec:
  template:
    metadata:
      name: myapp-pod
      labels: 
      # if it matches correctly they will function
        app: App1
        type: Front-end # Tagear el label pa que lo encuentre con el selector
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3 # cantidad de replicas que se van a hacer
  selector: # Por que puede agarrar pods que fueron creados en otro lado diferencia entre controller y replica set
    matchLabels: 
      type: Front-end # Significa que va a agarrar todos los pods que sean de tipo front-end incluso los que ya existian
