apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp # labels on the pod
  ports:
  - targetPort: 80 # The one at the pod
    port: 80 # the one at the service object the only one mandatory
    nodePort: 30008 # Nodeport the port on the node

# kubectl create -f service.yaml
# kubectl get services

# curl node:30008

