apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp
    
spec:
  containers:
    - name: data-processor
      image: data-processor
  nodeSelector:
    size: Large #labels


# kubectl label nodes node-name key=value

# kubectl label nodes node-1 size=large


