#kubectl create serviceaccount dashboard-sa

#kubectl get serviceaccount

#kubectl describe secret dashboard-sa-token-kbbdm

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp
    
spec:
  containers:
    - name: nginx-container
      image: nginx
  serviceAccountName: dashboard-sa
  automountServiceAccountToken: false

# que es We just added additional permissions for the newly created dashboard-sa account using RBAC.