apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
spec:
  containers:
    - name: nginx-container
      image: nginx
  serviceAccountName: dashboard-sa
  automountServiceAccountToken: false

  # it must have the permissions