apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp
    
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080
      # for http 
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
      # for tcp
      readinessProbe:
        tcpSocket:
          port: 3306
      # exec command
      readinessProbe:
        exec:
          command:
            - cat
            - /app/is_ready
