apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp
    
spec:
  containers:
  - name: nginx-container
    image: nginx
  - name : log-agent
    image: log-agent
    
      
# sidecar loggin service deploying a loggin agent to collect logs and foward them to a central server 
# adapter process de logs to arrange them for being send to a central server
# ambasador application communicates to a local database instance depending on the situation

apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]