apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: myapp
    type: backend
  ports:
  - port: 80
    targetPort: 80

# kubectl create -f service.yaml
# kubectl get services
# use the cluster ip or the service name to access