apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-job
spec:
  schedule: "*/1  * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-job
spec:
  schedule: "*/1  * * * *"
  jobTemplate: 
    spec:
      backoffLimit: 12
      completions: 3
      parallelism: 3
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: kodekloud/throw-dice
            name: throw-dice-job
            resources: {}
          restartPolicy: Never
    status: {}