apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    app: myapp
    
spec:
  containers:
    - name: nginx-container
      image: nginx
      
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-11-02T17:20:50Z"
  name: ubuntu-sleeper
  namespace: default
  resourceVersion: "702"
  uid: b5c632b8-3885-4558-b8b9-3a91f2cb94b2
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu